name: antill_estates
description: "Antill Estates - Premium Property Solution"
publish_to: 'none'
# Flutter Version: 3.32.2
# Dart Version: 3.8.1
version: 1.0.1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.7.2
  pinput: ^5.0.1
  google_maps_flutter: ^2.12.3
  visibility_detector: ^0.4.0+2
  dotted_border: ^3.0.1
  flutter_rating_bar: ^4.0.1
  get_storage: ^2.1.1
  image_picker: ^1.1.2
  share_plus: ^11.0.0
  url_launcher: ^6.3.1
  firebase_core: ^3.6.0   # use the latest version
  firebase_auth: ^5.7.0
  firebase_app_check: ^0.3.0+2   # (check latest)
  cloud_firestore: ^5.6.12
  firebase_messaging: ^15.1.3
  permission_handler: ^11.0.1
  http: ^1.1.0
  firebase_storage: 12.4.10
  shared_preferences: ^2.5.3
  cached_network_image: ^3.3.1
  crypto: ^3.0.3
  path_provider: ^2.1.4
  path: ^1.9.0
  flutter_local_notifications: ^18.0.1
  # Image optimization dependencies
  image: ^4.1.7
  flutter_image_compress: ^2.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_gen: ^5.4.0
  flutter_gen_runner: ^5.4.0
  build_runner: ^2.4.9
  # Performance optimization tools
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/flags/

  fonts:
    - family: Inter-Regular
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
    - family: Inter-Medium
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf
    - family: Inter-SemiBold
      fonts:
        - asset: assets/fonts/Inter-SemiBold.ttf
    - family: Inter-Bold
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
